name: financesensei
description: "Personal Financial Operating System - Offline first"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # State Management
  provider: ^6.1.1

  # Formatting
  intl: ^0.19.0

  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
